### ISSUE TITLE
add possibility to add to cart

### ISSUE THREAD

**Issue by ACharchula** [ACharchula/PIK-predator#71]
commit https://github.com/ACharchula/PIK-predator/commit/f8cb74fedfc98d667ef059620d1ab420c445fb8b

**Comment by tokerson** [comment]
commit https://github.com/ACharchula/PIK-predator/commit/317ed18a1fddd507f71dd8cdaabaf67bc7e02c22

**Comment by tokerson** [comment]
https://github.com/ACharchula/PIK-predator/pull/87

**Comment by tokerson** [comment]
https://github.com/ACharchula/PIK-predator/pull/88 with one small improvement ( round icon with the number of products )

**Comment by tokerson** [comment]
https://github.com/ACharchula/PIK-predator/pull/90
